const MONGO_URI = process.env.MONGO_URI;
const PORT = process.env.PORT;
const TOKEN_KEY = process.env.TOKEN_KEY;
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

module.exports = {
	MONGO_URI,
	PORT,
	TOKEN_KEY,
	CLOUDINARY_CLOUD_NAME,
	CLOUDINARY_API_KEY,
	CLOUDINARY_API_SECRET,
};
